#!/bin/bash
# Quick Deploy - One-command GCP deployment for qm-nmr-calc
#
# This script guides you through the complete deployment process:
#   1. Checks prerequisites (gcloud, auth, billing, APIs)
#   2. Creates infrastructure (IP, firewall, disk)
#   3. Prompts for DNS configuration
#   4. Validates DNS propagation
#   5. Deploys the VM
#   6. Verifies the deployment
#
# Usage:
#   ./quick-deploy.sh
#
# For experienced users who want more control, use individual scripts:
#   ./check-prerequisites.sh
#   ./setup-infrastructure.sh
#   ./check-dns.sh <domain>
#   ./deploy-vm.sh
#   ./verify-deployment.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo_info() { echo -e "${GREEN}[✓]${NC} $1"; }
echo_warn() { echo -e "${YELLOW}[!]${NC} $1"; }
echo_error() { echo -e "${RED}[✗]${NC} $1"; }
echo_step() { echo -e "${CYAN}[STEP]${NC} $1"; }
echo_prompt() { echo -e "${BLUE}[INPUT]${NC} $1"; }

# ============================================================================
# Welcome
# ============================================================================
clear
echo ""
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                                                                   ║"
echo "║           QM NMR Calculator - GCP Quick Deploy                    ║"
echo "║                                                                   ║"
echo "║   This wizard will guide you through deploying qm-nmr-calc        ║"
echo "║   to Google Cloud Platform using a cost-effective Spot VM.        ║"
echo "║                                                                   ║"
echo "║   Estimated cost: \$30-50/month (Spot VM + storage)                ║"
echo "║                                                                   ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""

read -r -p "Press Enter to continue or Ctrl+C to exit..."
echo ""

# ============================================================================
# Step 1: Check/create config.sh
# ============================================================================
echo_step "Step 1/6: Configuration"
echo ""

if [[ ! -f "config.sh" ]]; then
    echo "No config.sh found. Let's create one."
    echo ""

    # Check gcloud is installed
    if ! command -v gcloud &>/dev/null; then
        echo_error "gcloud CLI is not installed"
        echo ""
        echo "Install the Google Cloud SDK first:"
        echo "  macOS:   brew install google-cloud-sdk"
        echo "  Linux:   curl https://sdk.cloud.google.com | bash"
        echo ""
        exit 1
    fi

    # Check authentication
    ACTIVE_ACCOUNT=$(gcloud auth list --filter=status:ACTIVE --format="value(account)" 2>/dev/null || true)
    if [[ -z "$ACTIVE_ACCOUNT" ]]; then
        echo_warn "Not authenticated with gcloud"
        echo ""
        echo "Please authenticate:"
        gcloud auth login
        echo ""
    fi

    # Get project ID
    echo_prompt "Enter your GCP Project ID"
    echo "(Find at: https://console.cloud.google.com -> Project selector)"
    read -r -p "Project ID: " GCP_PROJECT_ID

    if [[ -z "$GCP_PROJECT_ID" ]]; then
        echo_error "Project ID is required"
        exit 1
    fi

    # Validate project access
    if ! gcloud projects describe "$GCP_PROJECT_ID" &>/dev/null; then
        echo_error "Cannot access project '$GCP_PROJECT_ID'"
        echo "Check the project ID and your permissions."
        exit 1
    fi

    # Get region/zone
    echo ""
    echo_prompt "Select region (press Enter for default)"
    read -r -p "Region [us-central1]: " GCP_REGION
    GCP_REGION="${GCP_REGION:-us-central1}"

    echo_prompt "Select zone (press Enter for default)"
    read -r -p "Zone [${GCP_REGION}-a]: " GCP_ZONE
    GCP_ZONE="${GCP_ZONE:-${GCP_REGION}-a}"

    # Create config.sh
    cat > config.sh <<EOF
#!/bin/bash
# GCP Configuration for qm-nmr-calc
# Generated by quick-deploy.sh on $(date)

GCP_PROJECT_ID="$GCP_PROJECT_ID"
GCP_REGION="$GCP_REGION"
GCP_ZONE="$GCP_ZONE"
RESOURCE_PREFIX="qm-nmr-calc"
DISK_SIZE_GB="100"
EOF

    echo ""
    echo_info "Created config.sh"
else
    echo_info "config.sh exists"
    source ./config.sh
    echo "  Project: $GCP_PROJECT_ID"
    echo "  Region:  $GCP_REGION"
    echo "  Zone:    $GCP_ZONE"
fi

echo ""
read -r -p "Press Enter to continue..."
echo ""

# ============================================================================
# Step 2: Check prerequisites
# ============================================================================
echo_step "Step 2/6: Checking Prerequisites"
echo ""

if ! ./check-prerequisites.sh; then
    echo ""
    echo_error "Prerequisites check failed. Fix the issues above and try again."
    exit 1
fi

echo ""
read -r -p "Press Enter to continue..."
echo ""

# ============================================================================
# Step 3: Setup infrastructure
# ============================================================================
echo_step "Step 3/6: Creating Infrastructure"
echo ""

# Source config
source ./config.sh
gcloud config set project "$GCP_PROJECT_ID" --quiet

# Check if infrastructure already exists
IP_NAME="${RESOURCE_PREFIX}-ip"
EXISTING_IP=$(gcloud compute addresses describe "$IP_NAME" --region="$GCP_REGION" --format="value(address)" 2>/dev/null || true)

if [[ -n "$EXISTING_IP" ]]; then
    echo_info "Infrastructure already exists"
    echo "  Static IP: $EXISTING_IP"
    STATIC_IP="$EXISTING_IP"
else
    echo "Creating infrastructure (static IP, firewall rules, disk)..."
    echo ""
    ./setup-infrastructure.sh
    STATIC_IP=$(gcloud compute addresses describe "$IP_NAME" --region="$GCP_REGION" --format="value(address)")
fi

echo ""
echo "=============================================="
echo "  IMPORTANT: Configure DNS Now"
echo "=============================================="
echo ""
echo "Before continuing, you need to point your domain to this IP address:"
echo ""
echo "  Static IP: $STATIC_IP"
echo ""
echo "Create a DNS A record in your domain registrar:"
echo "  Type:  A"
echo "  Name:  nmr (or @ for root domain)"
echo "  Value: $STATIC_IP"
echo "  TTL:   300"
echo ""
echo "Example: nmr.example.com -> $STATIC_IP"
echo ""

read -r -p "Press Enter once you've configured DNS..."
echo ""

# ============================================================================
# Step 4: Get domain and check DNS
# ============================================================================
echo_step "Step 4/6: DNS Validation"
echo ""

echo_prompt "Enter your domain name (e.g., nmr.example.com)"
read -r -p "Domain: " DOMAIN

if [[ -z "$DOMAIN" ]]; then
    echo_error "Domain is required"
    exit 1
fi

echo ""
echo "Checking DNS propagation..."
echo "(This may take a few minutes if you just configured DNS)"
echo ""

MAX_RETRIES=12
RETRY_INTERVAL=10
RETRY=0

while [[ $RETRY -lt $MAX_RETRIES ]]; do
    # Check DNS resolution
    RESOLVED_IP=""
    if command -v dig &>/dev/null; then
        RESOLVED_IP=$(dig +short "$DOMAIN" A 2>/dev/null | head -1 || true)
    elif command -v host &>/dev/null; then
        RESOLVED_IP=$(host "$DOMAIN" 2>/dev/null | grep "has address" | head -1 | awk '{print $4}' || true)
    fi

    if [[ "$RESOLVED_IP" == "$STATIC_IP" ]]; then
        echo ""
        echo_info "DNS verified: $DOMAIN -> $STATIC_IP"
        break
    elif [[ -n "$RESOLVED_IP" ]]; then
        echo_warn "Domain resolves to $RESOLVED_IP (expected: $STATIC_IP)"
        echo "Waiting for DNS to propagate..."
    else
        echo "Domain not resolving yet... (attempt $((RETRY+1))/$MAX_RETRIES)"
    fi

    ((RETRY++))
    if [[ $RETRY -lt $MAX_RETRIES ]]; then
        sleep $RETRY_INTERVAL
    fi
done

if [[ "$RESOLVED_IP" != "$STATIC_IP" ]]; then
    echo ""
    echo_warn "DNS did not propagate within the timeout"
    echo ""
    echo "Options:"
    echo "  1. Wait and try again (DNS can take up to 15 minutes)"
    echo "  2. Check your DNS settings"
    echo "  3. Continue anyway (Let's Encrypt may fail)"
    echo ""
    read -r -p "Continue with deployment? (yes/no) [no]: " CONTINUE
    CONTINUE="${CONTINUE:-no}"
    if [[ "$CONTINUE" != "yes" ]]; then
        echo ""
        echo "Run this script again when DNS is ready."
        exit 0
    fi
fi

echo ""
read -r -p "Press Enter to deploy the VM..."
echo ""

# ============================================================================
# Step 5: Deploy VM
# ============================================================================
echo_step "Step 5/6: Deploying VM"
echo ""

# Check if VM already exists
VM_NAME="${RESOURCE_PREFIX}-vm"
if gcloud compute instances describe "$VM_NAME" --zone="$GCP_ZONE" &>/dev/null; then
    echo_warn "VM '$VM_NAME' already exists"
    echo ""
    read -r -p "Delete and recreate? (yes/no) [no]: " RECREATE
    RECREATE="${RECREATE:-no}"
    if [[ "$RECREATE" == "yes" ]]; then
        echo "Deleting existing VM..."
        gcloud compute instances delete "$VM_NAME" --zone="$GCP_ZONE" --quiet
    else
        echo "Using existing VM."
    fi
fi

# Deploy if VM doesn't exist
if ! gcloud compute instances describe "$VM_NAME" --zone="$GCP_ZONE" &>/dev/null; then
    echo "Machine type options:"
    echo "  e2-standard-2   (2 vCPU, 8 GB)   ~\$15-25/month - Light workloads"
    echo "  e2-standard-4   (4 vCPU, 16 GB)  ~\$30-50/month - Recommended"
    echo "  n2-standard-4   (4 vCPU, 16 GB)  ~\$50-80/month - Higher performance"
    echo ""
    read -r -p "Machine type [e2-standard-4]: " MACHINE_TYPE
    MACHINE_TYPE="${MACHINE_TYPE:-e2-standard-4}"

    echo ""
    echo "Creating VM..."
    echo ""

    DISK_NAME="${RESOURCE_PREFIX}-data"

    gcloud compute instances create "$VM_NAME" \
        --zone="$GCP_ZONE" \
        --machine-type="$MACHINE_TYPE" \
        --provisioning-model=SPOT \
        --instance-termination-action=STOP \
        --tags="${RESOURCE_PREFIX}-vm" \
        --network-interface="address=$STATIC_IP" \
        --boot-disk-size=20GB \
        --boot-disk-type=pd-balanced \
        --image-family=debian-12 \
        --image-project=debian-cloud \
        --disk="name=${DISK_NAME},mode=rw,device-name=data-disk,boot=no,auto-delete=no" \
        --metadata-from-file=startup-script=startup.sh,shutdown-script=shutdown.sh \
        --metadata="DOMAIN=${DOMAIN}"

    echo ""
    echo_info "VM created!"
fi

echo ""
echo "Waiting for VM to start and containers to initialize..."
echo "(This takes 2-3 minutes)"
echo ""

# Wait for startup
sleep 30

echo "Checking startup progress..."
for i in {1..6}; do
    STARTUP_STATUS=$(gcloud compute ssh "$VM_NAME" --zone="$GCP_ZONE" --quiet \
        --command="tail -3 /var/log/startup-script.log 2>/dev/null || echo 'starting'" 2>/dev/null || echo "connecting")

    if [[ "$STARTUP_STATUS" == *"VM Setup Complete"* ]] || [[ "$STARTUP_STATUS" == *"Startup script finished"* ]]; then
        echo ""
        echo_info "Startup complete!"
        break
    fi

    echo "  Still initializing... ($((i*30))s)"
    sleep 30
done

echo ""
read -r -p "Press Enter to verify deployment..."
echo ""

# ============================================================================
# Step 6: Verify deployment
# ============================================================================
echo_step "Step 6/6: Verifying Deployment"
echo ""

./verify-deployment.sh

echo ""
echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                                                                   ║"
echo "║                    Deployment Complete!                           ║"
echo "║                                                                   ║"
echo "╠═══════════════════════════════════════════════════════════════════╣"
echo "║                                                                   ║"
echo "║   Access your deployment at:                                      ║"
echo "║   https://$DOMAIN"
echo "║                                                                   ║"
echo "║   Useful commands:                                                ║"
echo "║     ./status-vm.sh     - Check VM status                          ║"
echo "║     ./stop-vm.sh       - Stop VM (saves money when not in use)    ║"
echo "║     ./start-vm.sh      - Start VM again                           ║"
echo "║     ./logs-vm.sh       - View container logs                      ║"
echo "║     ./ssh-vm.sh        - SSH into VM                              ║"
echo "║                                                                   ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
